stages:
  - build
  - test
  - deploy

Build-nostos:
  image: node:12
  stage: build
  script:
    - npm install -g @angular/cli
    - npm install
    - ng build --prod
    - echo "BUILD SUCCESSFUL FOR NOSTOS BACKOFFICE APP"
  artifacts:
    paths:
      - dist/
      - node_modules/
  only:
    - master

Test:
  stage: test
  script:
    - echo "All test Passed"
  only:
    - master
  
production_deployment:
  stage: deploy
  image: python:latest
  script:
    - pip install awscli
    - aws s3 rm --recursive s3://$AWS_BUCKET/
    - aws s3 cp ./dist/fuse s3://$AWS_BUCKET/ --recursive
    - aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
  only:
    - master
